
#define SYS_fork    1
#define SYS_spawn   2
#define SYS_wait    3
#define SYS_exit    4
#define SYS_getpid  5
#define SYS_sleep   6
#define SYS_open    7
#define SYS_close   8
#define SYS_read    9
#define SYS_write   10
#define SYS_link    11
#define SYS_unlink  12
#define SYS_mkdir   13
#define SYS_chdir   14
#define SYS_readdir 15
#define SYS_rmdir   16
#define SYS_fstat   17
#define SYS_sbrk    18
#define SYS_meminfo 19
#define SYS_dup     20
#define SYS_pipe    21
#define SYS_info    22
#define SYS_halt    23
